fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    puppetdb: "https://github.com/puppetlabs/puppetlabs-puppetdb.git"
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    file_concat: "https://github.com/electrical/puppet-lib-file_concat.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"

  symlinks:
    profile_puppetmaster: "#{source_dir}"
